language: ruby
rvm:
  - 3.0.3
gemfile:
  - gemfiles/rails_6.1.4_mysql2_driver.gemfile
  - gemfiles/rails_6.1.4_pg_driver.gemfile
  - gemfiles/rails_6.1.4_sqlite3_driver.gemfile
before_script:
  - "mysql -e 'create database pacecar_test;' >/dev/null"
  - "psql -c 'create database pacecar_test;' -U postgres >/dev/null"
notifications:
  email: false
sudo: false
